// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero_example

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_logo, &ui_img_zero_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_logo, 5);
    lv_obj_set_y(ui_logo, 5);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_time, &ui_img_time_png);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_time, 237);
    lv_obj_set_y(ui_time, 5);
    lv_obj_add_flag(ui_time, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLabel = lv_label_create(ui_time);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "15:21");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_power, &ui_img_power_png);
    lv_obj_set_width(ui_power, LV_SIZE_CONTENT);   /// 29
    lv_obj_set_height(ui_power, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_power, 286);
    lv_obj_set_y(ui_power, 5);
    lv_obj_add_flag(ui_power, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_power, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_power);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "96%");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_appname = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_appname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_appname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_appname, -10);
    lv_obj_set_y(ui_appname, -74);
    lv_obj_set_align(ui_appname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_appname, "APPNmae");
    lv_obj_set_style_text_color(ui_appname, lv_color_hex(0x8D44FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_appname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apppage = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_apppage);
    lv_obj_set_width(ui_apppage, 320);
    lv_obj_set_height(ui_apppage, 143);
    lv_obj_set_x(ui_apppage, 0);
    lv_obj_set_y(ui_apppage, 13);
    lv_obj_set_align(ui_apppage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_apppage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_apppage);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "heloworld");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF2626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
