// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero_example

#ifndef _ZERO_EXAMPLE_UI_H
#define _ZERO_EXAMPLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

#define lv_mem_alloc lv_malloc
#define lv_mem_free   lv_free
#define lv_event_send(obj, evt, param) lv_obj_send_event(obj, evt, param)

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_power;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_appname;
extern lv_obj_t * ui_apppage;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_zero_png);    // assets/zero.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_power_png);    // assets/power.png

// FONTS

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
