from pathlib import Path
import os
import shutil
import socket


if False:
    if not os.path.exists('build/config/config_tmp.mk'):
        os.makedirs('build/config', exist_ok=True)
        with open('build/config/config_tmp.mk', 'w') as f:
            f.write('CONFIG_V9_5_LV_USE_LINUX_FBDEV=y\n')
            f.write('CONFIG_V9_5_LV_DRAW_SW_ASM_NEON=y\n')
            f.write('CONFIG_V9_5_LV_USE_DRAW_SW_ASM=1\n')
            f.write('CONFIG_V9_5_LV_USE_EVDEV=y\n')

            # f.write('CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin"\n')
            f.write('CONFIG_TOOLCHAIN_PREFIX="aarch64-linux-gnu-"\n')



if True:
    if not os.path.exists('build/config/config_tmp.mk'):
        os.makedirs('build/config', exist_ok=True)
        with open('build/config/config_tmp.mk', 'w') as f:
            f.write('CONFIG_V9_5_LV_USE_SDL=y\n')

if False:
    if not os.path.exists('build/config/config_tmp.mk'):
        os.makedirs('build/config', exist_ok=True)
        with open('build/config/config_tmp.mk', 'w') as f:
            f.write('CONFIG_V9_5_LV_USE_LINUX_FBDEV=y\n')





local_path = Path(os.getcwd())
sdk_path = local_path.parent.parent / 'SDK'
os.environ['SDK_PATH'] = str(sdk_path)
os.environ['EXT_COMPONENTS_PATH'] = str(sdk_path.parent / 'ext_components')


env = SConscript(
    str(sdk_path / 'tools' / 'scons' / 'project.py'),
    variant_dir=os.getcwd(),
    duplicate=0,
)
